### ISSUE TITLE
Get tendermint hash in querying instead of EE hash

### ISSUE THREAD

**Issue by psy2848048** [hdac-io/friday#27]
### As-is
**EE hash** as a query parameter

### To-be
**Tendermint block hash** as  a query parameter

**Comment by JoowonYun** [comment]
I prefer hash. This is because the separated phenomenon of the chain can be confirmed.
I hope to support both.

**Comment by psy2848048** [comment]
Fix is pushed at https://github.com/hdac-io/friday/pull/45
