### ISSUE TITLE
Remained README unaligned command

### ISSUE THREAD

**Issue by psy2848048** [hdac-io/friday#53]
1. `./clif` (should be `clif`)
1. Wrong example in transfer
    * `--token-contract-address` instead of `--token_contract_address`
    * Need to add options in example
1. Different `bond` cmd usage
    * Main usage
    * Create validator

**Comment by JoowonYun** [comment]
Need to change incorrect example

>> clif executionlayer transfer --from elsa --to-name sisteranna 1000000 100000000 20000000

**Comment by psy2848048** [comment]
Merged into master
