### ISSUE TITLE
Structure of address

### ISSUE THREAD

**Issue by JoowonYun** [hdac-io/friday#98]
Currently, we are creating an address prefixed to the existing 20 bytes.

However, when a contract or account is created in execution-engine, 32 bytes different from our prefix are generated.

The address structure needs to be re-discussed for use in the platform.

**Comment by psy2848048** [comment]
Will be fixed with https://github.com/hdac-io/friday/pull/111

**Comment by psy2848048** [comment]
Resolved as https://github.com/hdac-io/friday/pull/127
